addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo" % "0.9.0" )
addSbtPlugin("com.github.gseitz" % "sbt-release"   % "1.0.7" )
addSbtPlugin("com.jsuereth"      % "sbt-pgp"       % "1.1.0" )
addSbtPlugin("org.scala-js"      % "sbt-scalajs"   % "0.6.32")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"  % "2.3.1" )
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"  % "2.1"   )
