addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo" % "0.7.0"  )
addSbtPlugin("com.geirsson"      % "sbt-scalafmt"  % "1.4.0"  )
addSbtPlugin("com.github.gseitz" % "sbt-release"   % "1.0.7"  )
addSbtPlugin("com.jsuereth"      % "sbt-pgp"       % "1.1.0"  )
addSbtPlugin("com.thesamet"      % "sbt-protoc"    % "0.99.14")
addSbtPlugin("org.scala-js"      % "sbt-scalajs"   % "0.6.21" )
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"  % "2.1"    )
