addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo" % "0.8.0" )
addSbtPlugin("com.geirsson"      % "sbt-scalafmt"  % "1.4.0" )
addSbtPlugin("com.github.gseitz" % "sbt-release"   % "1.0.7" )
addSbtPlugin("com.jsuereth"      % "sbt-pgp"       % "1.1.0" )
addSbtPlugin("org.scala-js"      % "sbt-scalajs"   % "0.6.22")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"  % "2.1"   )
